# Generated by Django 4.2.23 on 2025-09-01 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_accountstatus_clientaccount_supportticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingtask',
            options={'ordering': ['tenant', 'order']},
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='tenant',
            field=models.ForeignKey(default='92ea31bc-9df1-4e55-aaf1-fa1ae4eec932', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='rbac.tenant'),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='tenant',
            field=models.ForeignKey(default='92ea31bc-9df1-4e55-aaf1-fa1ae4eec932', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='rbac.tenant'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='tenant',
            field=models.ForeignKey(default='92ea31bc-9df1-4e55-aaf1-fa1ae4eec932', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='rbac.tenant'),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='client_account',
            field=models.ForeignKey(blank=True, help_text='Optional: VacationDesktop internal account record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks', to='rbac.clientaccount'),
        ),
        migrations.AlterField(
            model_name='salesopportunity',
            name='client_account',
            field=models.ForeignKey(blank=True, help_text='Optional: VacationDesktop internal account record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='rbac.clientaccount'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['SUPER_ADMIN', 'SYSTEM_ADMIN', 'HELPDESK_USER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='client_account',
            field=models.ForeignKey(blank=True, help_text='Optional: VacationDesktop internal account record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='rbac.clientaccount'),
        ),
    ]
