# Generated by Django 4.2.23 on 2025-09-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_onboardingtask_options_onboardingtask_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL_EXPIRED', 'Trial Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('PENDING_SETUP', 'Pending Setup')], default='PENDING_SETUP', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('TRIAL', 'Trial'), ('CLIENT', 'Paying Client')], default='PROSPECT', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='rbac.tenant'),
        ),
        migrations.AlterField(
            model_name='salesopportunity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='rbac.tenant'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='rbac.tenant'),
        ),
    ]
