# Generated by Django 4.2.23 on 2025-09-01 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_tenant_status_tenant_tenant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='created_for',
            field=models.ForeignKey(blank=True, help_text='Client user this ticket was created for (receives notifications)', limit_choices_to={'role__is_system_role': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_for_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by',
            field=models.ForeignKey(help_text='Staff member who created this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
