# Generated by Django 4.2.23 on 2025-09-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vip_status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('PREMIUM', 'Premium')], default='REGULAR', max_length=20),
        ),
    ]
