# Generated by Django 4.2.23 on 2025-09-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0002_alter_client_vip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='custom_trip_type',
            field=models.CharField(blank=True, help_text="Custom trip type when 'Other' is selected", max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('SENT_TO_CLIENT', 'Sent to Client'), ('WORKING_ON_IT', 'Working On It'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('CRUISE', 'Cruise'), ('TOUR', 'Tour'), ('ALL_INCLUSIVE', 'All-Inclusive Resort'), ('CONDO_RENTAL', 'Condo/Vacation Rental'), ('HOTEL', 'Hotel Stay'), ('ADVENTURE', 'Adventure Travel'), ('BUSINESS', 'Business Travel'), ('HONEYMOON', 'Honeymoon'), ('FAMILY', 'Family Vacation'), ('GROUP', 'Group Travel'), ('OTHER', 'Other')], default='CRUISE', max_length=20),
        ),
    ]
