# Generated by Django 4.2.23 on 2025-09-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0003_trip_custom_trip_type_alter_trip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget range', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget range', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual total amount', max_digits=10, null=True),
        ),
    ]
