# Generated by Django 4.2.23 on 2025-09-10 23:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0004_trip_budget_range_max_trip_budget_range_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('CRUISE', 'Cruise'), ('AIRFARE', 'Airfare'), ('HOTEL', 'Hotel/Accommodation'), ('TRANSFER', 'Transfer/Transportation'), ('EXCURSION', 'Shore Excursion/Tour'), ('INSURANCE', 'Travel Insurance'), ('VISA', 'Visa/Documentation'), ('RENTAL_CAR', 'Rental Car'), ('DINING', 'Dining/Meals'), ('ACTIVITIES', 'Activities/Entertainment'), ('FEES', 'Fees/Taxes'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('supplier', models.CharField(blank=True, help_text='Cruise line, airline, hotel, etc.', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, help_text='Date of service/departure', null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='business_management.trip')),
            ],
            options={
                'db_table': 'trip_line_items',
                'ordering': ['item_type', 'service_date', 'description'],
            },
        ),
    ]
