# Generated by Django 4.2.23 on 2025-09-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0005_triplineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitinerary',
            name='description',
            field=models.TextField(blank=True, help_text='Day description and activities'),
        ),
        migrations.AddField(
            model_name='tripitinerary',
            name='title',
            field=models.CharField(blank=True, help_text='Day title', max_length=200),
        ),
    ]
