# Generated by Django 4.2.23 on 2025-09-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0006_tripitinerary_description_tripitinerary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, help_text='Trip description to be included in client emails'),
        ),
    ]
